name: Pattern2
on:
  push:
    paths:
      - '.github/workflows/pattern2.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pattern2
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/dev-sample-actions-user-2-role
          role-duration-seconds: 1200
          role-session-name: assume
      - name: Check
        run: |
          aws s3 ls