name: Pattern1
on:
  push:
    paths:
      - '.github/workflows/pattern1.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pattern1
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Check
        run: |
          aws s3 ls